# Generated by Django 5.0.7 on 2024-07-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='https://www.shutterstock.com/image-vector/default-image-icon-vector-missing-260nw-2086941550.jpg', upload_to='project_images/'),
        ),
    ]
